name: API Tests and Report

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: List directory contents
      run: ls -R

    - name: Print testng.xml content
      run: cat testng.xml

    - name: Build and Test with Maven
      run: mvn clean test -X

    - name: List test-output directory
      run: ls -R test-output
      if: always()

    - name: Upload test results
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: test-results
        path: target/test-output/ExtentReport.html